# Generated by Django 5.2.8 on 2026-02-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uin', models.CharField(max_length=255, unique=True)),
                ('firstName', models.TextField(null=True)),
                ('lastName', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('ip', models.CharField(max_length=30)),
                ('public_key', models.CharField(blank=True, max_length=130, null=True)),
                ('manufacturer', models.TextField(null=True)),
                ('csr', models.TextField(blank=True, null=True)),
                ('challengeCount', models.SmallIntegerField(default=0)),
                ('interval', models.SmallIntegerField(default=1000000)),
                ('certificate', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
