# Generated by Django 5.2.8 on 2026-01-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('public_key', models.CharField(max_length=130)),
            ],
        ),
    ]
