# Generated by Django 5.2.8 on 2026-02-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0002_device_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('suspended', 'Suspended')], default='connected', max_length=20),
        ),
    ]
