# Generated by Django 6.0.1 on 2026-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0003_device_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='connected', max_length=20),
        ),
    ]
