# Generated by Django 5.2.8 on 2026-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0003_device_csr_alter_device_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.TextField(null=True),
        ),
    ]
