# Generated by Django 5.2.8 on 2026-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0004_device_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
