# Generated by Django 5.2.8 on 2026-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0004_device_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='challengeCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='interval',
            field=models.SmallIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='device',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
