# Generated by Django 5.2.8 on 2026-02-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0004_alter_device_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='interval',
            field=models.SmallIntegerField(default=10000),
        ),
    ]
