# Generated by Django 5.2.8 on 2026-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0002_device_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='csr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
