# Generated by Django 5.2.8 on 2026-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idverification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
